### ISSUE TITLE
What is this project results on detection tasks?

### ISSUE THREAD

**Issue by zeng-hello-world** [Roll920/CURL#1]
First, thanks for your brilliant work.
For such pruning methods, whether detection tasks can also use this? Have you done some experiments on them?

Thanks!

**Comment by Roll920** [comment]
@zeyu-hello Hi zeyu, I have not done such an experiment.
For detection task, you can use the pruned network as the backbone model.
If you use this method to prune the trained model on detection, it may work. But I am not sure.

**Comment by zeng-hello-world** [comment]
@Roll920 Hi, thanks for quikly reply!
I have tried other pruing methods on backbone before training detection tasks as you said. 
Maybe for detection tasks, this is a conventionalized strategy.

Another issue is the compression rate in your paper, you keep at least 30% wieghts. But I have got like only 1 channel for some layer after pruning with other pruning method, this might reach 90% pruning rate for this layer. So why not keep at least 1 channel in your experiment?

Thanks

**Comment by Roll920** [comment]
@zeyu-hello 
If we only preserve several channels (e.g., 1 channel as you said), the accuracy may be low (I have not verified this conclusion due to CVPR ddl).
Maybe you can try it, remove this constraint (30%) and see whether the accuracy will be lower.
